# Generated by Django 4.2.2 on 2023-07-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('rubrique_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.TextField()),
                ('libelle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtHelp',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.TextField()),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=5)),
                ('product', models.CharField(max_length=10)),
                ('date_update', models.DateField()),
                ('title_embedding', models.BinaryField()),
                ('title_similarity', models.FloatField(null=True)),
                ('text_embedding', models.BinaryField()),
                ('text_similarity', models.FloatField(null=True)),
                ('computed_similarity', models.FloatField(null=True)),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scengine.rubrique')),
            ],
        ),
    ]
